version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    environment:
      - REDIS_DNS=redis
    depends_on:
      redis:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_DNS=backend
      - BACKEND_PORT=9000
    depends_on:
      - backend
    restart: always

volumes:
  redis-data:
