name: Publish Docker Images and Deploy

on:
  push:
    branches:
      - main

# Add permissions needed for GitHub Container Registry
permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
    
    - name: Build Frontend
      run: |
        cd frontend
        go build

    - name: Build Backend
      run: |
        cd backend
        go build

    # Login to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Frontend Docker Container
      run: |
        cd frontend
        docker build -t frontend:latest .
        docker tag frontend:latest ghcr.io/${{ github.repository_owner }}/fortune-cookie-frontend:latest
        docker push ghcr.io/${{ github.repository_owner }}/fortune-cookie-frontend:latest

    - name: Build and Push Backend Docker Container
      run: |
        cd backend
        docker build -t backend:latest .
        docker tag backend:latest ghcr.io/${{ github.repository_owner }}/fortune-cookie-backend:latest
        docker push ghcr.io/${{ github.repository_owner }}/fortune-cookie-backend:latest
        
    - name: Show Publish Status
      run: echo "Docker containers built and published successfully!"
    
    # Set up kubectl for deployment
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      
    # Configure kubectl with KUBECONFIG from secrets
    - name: Configure kubectl and deploy
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
        chmod 600 kubeconfig
        
        # Make deploy script executable
        chmod +x ./deploy.sh
        
        # Run deployment using the kubeconfig
        ./deploy.sh --kubeconfig kubeconfig --environment production
